### PR TITLE
Fix 'curl: (33) HTTP server doesn't seem to support byte ranges. Cannot resume.'

### PR DESCRIPTION
**Pull request by houtianze**

### CODE REVIEW

**Comment by smashedtoatoms** [comment]
Is this adding a Docker requirement to the installer?  That is a HUGE strategy shift for a tool whose current requirements are effectively bash.  Maybe I am misunderstanding the change?

**Comment by smashedtoatoms** [comment]
Actually, as I look closer at this, the Docker stuff isn't doing anything.  Is the only change the actual curl statement?  If so, can you nuke the gitpod stuff?

**Comment by houtianze** [comment]
Sorry, my bad. I thought I only created the PR for one file, didn't expect all the gitpod stuffs went in. Let me close this PR now.

**Comment by smashedtoatoms** [comment]
Oh you don't have to close it.  The change is perfect.  I just think gitpod is out of scope for this.

**Comment by houtianze** [comment]
Oh, it's OK. I don't like it to be so messy and created another clean PR :)

Regards,
Tianze

**Pull request closed without merging**
